
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://ruchiranga.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Ruchiranga Wickramasinghe"
title: "{ Ruchiranga }"
description: "Personal web space of Ruchiranga Wickramasinghe."
keywords: "thanuditha, ruchiranga, wickramasinghe, software engineer, tech, epfl, uom"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"
logo:  # leave blank if you don't want a logo

background-img: "../img/home-bg-ed2.png"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 1
start-delay: 0
delete-delay: 1000
lines: # You can add HTML Tags in the Text
  - text: "Software Engineer"
  - text: "Fullstack Developer"
  - text: "Tech Enthusiast"
  - text: "Avid Gamer"
  - text: "Music Lover"

me-img: "/img/trw_profile_photo_ed.jpg"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "personal-jekyll-theme"

syntax-highlight: True

############
# Timeline #
############

experience:
  - image: "/img/timeline/logitech.png"
    # date: "Mar. 2017 - Aug. 2018"
    date: "Logitech"
    description: "Software Engineering Intern"
  - image: "/img/timeline/syscolabs.jpg"
    # date: "Mar. 2017 - Aug. 2018"
    date: "SyscoLabs"
    description: "Software Engineer"
  - image: "/img/timeline/joomla.png"
    # date: "Apr. 2016 - Aug. 2016"
    date: "Joomla!"
    description: "Google Summer of Code 2016"
  - image: "/img/timeline/99x.png"
    # date: "Oct. 2015 - Apr. 2016"
    date: "99X Technology"
    description: "Trainee Software Engineer"
  - image: "/img/timeline/mbrainz.png"
    # date: "May 2015 - Aug. 2015"
    date: "Metabrainz Foundation"
    description: "Google Summer of Code 2015"

education:
  - image: "/img/timeline/epfl.png"
    # date: "Sept. 2018 - Apr. 2021"
    date: "Swiss Federal Institute of Technology Lausanne"
    description: "M.Sc. in Computer Science"
  - image: "/img/timeline/uom.png"
    # date: "Mar. 2013 - Apr. 2017"
    date: "Univeristy of Moratuwa"
    description: "B.Sc. in Computer Science & Engineering"

# First image of the Timeline

# timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "thanuditha.wickramasinghe@alumni.epfl.ch"


# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "John Smith is an awesome person. He lives in Flatland, where he works on two-dimensional engineering projects. In his spare time, John likes to eat cotton candy."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  # - title: "facebook"
  #   url: "https://facebook.com/"
  # - title: "twitter"
  #   url: "https://twitter.com/"
  - title: "github"
    url: "https://github.com/Ruchiranga"
  - title: "stack-overflow"
    url: "https://stackoverflow.com/users/3781850/truchiranga"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/ruchirangawickramasinghe/"
  # - title: "bitcoin"
  #   url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  # - title: "rss"
  #   url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

# keybase-username: truchiranga
# keybase-in-social: True
# keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Education: 'education'
  Experience: 'experience'
  Contact: 'contact'
#  Blog: 'latest-post'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji

plugins: [jekyll-paginate]